# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = insertsort.o
LINKOBJ  = insertsort.o
LIBS     = -L"E:/dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/dev-c++/Dev-Cpp/MinGW64/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/dev-c++/Dev-Cpp/MinGW64/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

insertsort.o: insertsort.c
	$(CC) -c insertsort.c -o insertsort.o $(CFLAGS)
